### ISSUE TITLE
Problem while looking for existing user.

### ISSUE THREAD

**Issue by denics** [jewflix/ansible-role-jackett#2]
Hi, thanks for this, it saves me lot of manual work. However, I found an error using a custom user, kodi, in my RPi 4:

```
TASK [jewflix.jackett : Ensure the jackett user is present] **********************************************************************************************************************************
fatal: [marte]: FAILED! => {"changed": false, "msg": "usermod: user kodi is currently used by process 588\n", "name": "kodi", "rc": 8}
```

I haven't found an answer myself :(

**Comment by tkimball83** [comment]
It looks like you're trying to install jackett as the kodi user?  Is there a reason for this?

Jackett does not need to share the same user as kodi for kodi to be able to access the application.

**Comment by tkimball83** [comment]
Closing due to lack of updates.
