### ISSUE TITLE
missing tar and unzip dependencies

### ISSUE THREAD

**Issue by dropsignal** [jewflix/ansible-role-jackett#3]
starting with a minimal install of rocky linux version 8. minimal install does not include tar or unzip. suspect the same for rhel and centos. please add tar and unzip as part of the install of the dependencies.

**Comment by dropsignal** [comment]
patch submitted and accepted

**Comment by tkimball83** [comment]
Tagged with [v0.1.3](https://github.com/jewflix/ansible-role-jackett/releases/tag/v0.1.3)
